(a) Creating Matrix A<br> 
N(10 − 2k, sqrt(2k)) , k = 1, 2, 3, 4, 5, for Even rows<br> 
logNormal( μ , 2k + 1) , k = 0, 1, 2, 3, 4 for Odd rows<br> 

μ =
<br> 
0.5(2k + 1), k = 0, 1, 2<br> 
0.1(2k + 1), k = 3, 4<br> 

In [104]:
import random
import math

def get_gausssian(mu, sigma):
    """ returns positive gausssian"""
    random_num = random.gauss(mu,sigma)
    while not (random_num>0):
        random_num = random.gauss(mu,sigma)
    return random_num

matrix = list()
for i in range(1, 11):
    if i%2 == 0: #Even Number
        radom_numbers = [get_gausssian(10-2*i, math.sqrt(2*i)) for _ in range(10)]
    else: #Odd Number
        k = i/2
        if k < 3:  #k = 0, 1, 2
            radom_numbers = np.random.lognormal(0.5*(2*k+1), math.sqrt(2*k+1), 10) 
        else:
            radom_numbers = np.random.lognormal(0.1*(2*k+1), math.sqrt(2*k+1), 10) 
    matrix.append(radom_numbers)

matrix_A = np.matrix(matrix)
matrix_A

matrix([[3.36423126e+00, 5.57801787e+00, 3.13372050e+00, 1.72782276e+00,
         7.70114197e+00, 1.15035438e-01, 3.89683059e-01, 4.01177670e+00,
         1.35261803e+01, 5.48347718e+00],
        [5.36714399e+00, 3.52326536e+00, 7.75021273e+00, 1.09023581e+01,
         5.58973118e+00, 7.87409405e+00, 5.74873837e+00, 8.33531951e+00,
         6.14525773e+00, 6.52465136e+00],
        [7.61386225e+00, 1.23200381e+00, 7.45174087e+00, 5.47739583e+01,
         1.46252678e+01, 6.16391300e+00, 1.07247886e+01, 1.97101888e+00,
         1.05831757e+00, 1.29393922e+01],
        [3.22652492e+00, 8.52963463e-01, 2.07280899e+00, 3.62891524e+00,
         7.88268257e+00, 6.13548883e+00, 5.41196334e+00, 6.06596466e+00,
         2.84903052e+00, 5.40776501e+00],
        [2.34820870e+01, 1.23033284e+01, 1.35870391e+00, 7.33368115e+01,
         1.01279358e+03, 6.24142861e+01, 4.35757966e+00, 1.25271599e+02,
         2.52407102e+02, 1.12863681e+00],
        [5.91493292e-01, 4.36327464e+00, 1.20097314e+00, 4.0

Generate a vector, B that is compatible to A using random
integers from the set, S = {s : 10 ≤ s ≤ 20} such that, the ma-
trix product

In [105]:
# matrix_B = np.random.randint(10,20,size=(10,10))
matrix_B = np.random.randint(10,20,size=(10,1))
matrix_B

array([[17],
       [19],
       [16],
       [17],
       [14],
       [12],
       [12],
       [18],
       [18],
       [10]])

In [106]:
matrix_C =  np.matmul(matrix_A, matrix_B)
matrix_C

matrix([[  727.07739393],
        [ 1035.15411001],
        [ 1794.56902135],
        [  629.38827768],
        [23691.29930159],
        [  311.70166064],
        [ 7760.86969919],
        [  332.1404544 ],
        [ 3733.38991838],
        [  263.09667511]])

NumPy’s broadcasting abilities are relevant/required

1. **Not required if the operations are performed on a single CPU system**
2. **Required in the case of parallel processing, can speed up the computation**


## ________________________

If A denotes the money spent on unit quantities of various items over
a 10-duration period, and B represents the constant consumption in
units of such items over each of this period, write a program that can
be used to provides answers to the following: <br>
i. The periods where the total costs of consumption are either
a minimum or a maximum, and their respective values;

In [108]:
print("Minimum consumption ", min(matrix_C))
print("Maximum consumption ", max(matrix_C))

('Minimum consumption ', matrix([[263.09667511]]))
('Maximum consumption ', matrix([[23691.29930159]]))


ii. Identify the product with minimum price variability, and the
product with maximum price variability;

In [109]:
min_variablity = max_variablity = None
min_product = max_product = None

for i in range(10):
    variablity = max(matrix_A[:,i])-min(matrix_A[:,i])
    
    if i == 0 :
        min_product = max_product= i
        min_variablity = max_variablity =  variablity
        
    if variablity > max_variablity:
        max_product = i
        max_variablity = variablity
        
    if min_variablity > variablity :
        min_product = i
        min_variablity = variablity
        
print("Product ", max_product, " has maximum price variablity ", max_variablity)
print("Product ", min_product, " has minimum price variablity ", min_variablity)

('Product ', 4, ' has maximum price variablity ', matrix([[1012.56600735]]))
('Product ', 2, ' has minimum price variablity ', matrix([[7.56834947]]))


iii. Evaluate the impact on the average cost of consumption, if
the consumption of products with minimum and maximum
variability that are identified above, are switched.

In [120]:
current_avg_consumption = np.average(matrix_C)
print("Current avg consumption of products ", current_avg_consumption)

#switching the products with minimum price variablity and maximum price variablity
products_comsumption = np.copy(matrix_A)
products_comsumption[:,min_product] = list(matrix_A[:,max_product])
products_comsumption[:,max_product] = list(matrix_A[:,min_product])

projected_avg_consumption = np.average(products_comsumption)
print("Projected avg consumption of products ", projected_avg_consumption)

('Current avg consumption of products ', 4027.868651226978)
('Projected avg consumption of products ', 27.656435345859123)


**If the consumption of the products with minimum and maximum variablity are switched, the average cost of consumption will go down.**<br>

(c) What is the outcome, and the significance of the following operation?

In [123]:
np.dot(matrix_A[0 : 5, :], matrix_B)

matrix([[  727.07739393],
        [ 1035.15411001],
        [ 1794.56902135],
        [  629.38827768],
        [23691.29930159]])

**A[0 : 5, :]B results in the total consumption of the first 5 products**

In relation to the above schema of costs and consumption, by carefully
setting out your assumptions and defining all terms used, <br>
i. define a mathematical problem that would seek to maximize
the consumers utility given a range of values representing her
budgetary constraints;

**(Similar to Averaging Down in trading) 
Additional products can be purchased when the price of the products goes below the mean/average and less products when the price is above the average**

ii. suggest how, using relevant NumPy or other system built-in
libraries, the above problem might be solved.


1. **Can decrease the time for validation of algorithms**
2. **Parallel processing - decreases time for validation**